name:                json5-hs
version:             0.1.0.0
github:              "githubuser/json5-hs"
license:             BSD3
author:              "Timo von Holtz"
maintainer:          "tvh@tvholtz.de"
copyright:           "2020 Timo von Holtz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tvh/json5-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.0.0
- megaparsec >= 8.0.0
- scientific >= 0.3
- text >= 1.2
- unordered-containers >= 0.2
- vector >= 0.12

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

tests:
  json5-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - json5-hs
    - bytestring >= 0.10
    - directory >= 1.3
    - filepath >= 1.4
    - inline-js >= 0.0.1.0
    - tasty >= 1.2
    - tasty-hunit >= 0.10
    - text >= 1.2
